@apiurl = "http://localhost:3000/telegram-bot/";

###
POST http://localhost:3000/telegram-bot/sendMessage/5746907442 HTTP/1.1
Content-Type: application/json

 {
  "message": "1, 2, 3, login!"
 }

###
POST http://localhost:3000/telegram-bot/webhook
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

####
GET http://localhost:3000/messages
Content-Type: application/json
